version: '3.8'

services:
  main:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - main_db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=main_db
      - DB_PORT=3306
      - DB_DATABASE=main
      - DB_USERNAME=root
      - DB_PASSWORD=root

  main_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33064:3306" 

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - main_db
    environment:
      PMA_HOST: main_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8088:80" 
