version: "3.9"

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "wait-for-it.sh main_db:3306 -- php artisan serve --host=0.0.0.0 --port=3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - main_db
    environment:
      - DB_HOST=main_db
      - DB_DATABASE=main
      - DB_USERNAME=root
      - DB_PASSWORD=root

    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

    networks:
      -  microservice-network

  main_phpmyadmin:
    container_name: main_phpmyadmin
    image: phpmyadmin:latest
    depends_on:
      - main_db
    environment:
      PMA_HOST: main_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5001:80"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
    networks:
      -  microservice-network

  main_queue:
    container_name: main_queue
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - main_db
    command: bash -c "wait-for-it.sh main_db:3306 -- php artisan queue:work rabbitmq --queue=main_queue"
    environment:
      - DB_HOST=main_db
      - DB_PORT=3306
      - DB_DATABASE=main
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_CONNECTION=mysql
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

    networks:
      -  microservice-network

  main_db:
    container_name: main_db
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --host_cache_size=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

    networks:
      -  microservice-network



networks:
  microservice-network:
    external: true