version: '3.9'

services:
  main:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - main_db
    environment:
      - DB_HOST=main_db
      - DB_DATABASE=main
      - DB_USERNAME=root
      - DB_PASSWORD=root

  main_phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - main_db
    environment:
      PMA_HOST: main_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5001:80"

  main_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
